spring:
  kafka:
    consumer:
      bootstrap-servers: 172.25.0.4:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer